### ISSUE TITLE
[Internal] Migrate server side code to ES6

### ISSUE THREAD

**Issue by js2me** [acacode/flamebird#24]
Use support table https://node.green/
Dont use `import` keywords (because it isn't support)
Use arrow functions where it needed,

**Comment by oncletom** [comment]
Have you tried https://www.npmjs.com/package/lebab?

It might be a sensible way to do it quickly and safely.

**Comment by js2me** [comment]
@oncletom I haven't tried `lebab`, it is a good idea, but I not sure that `lebab` is will not broke project
Because some ES6-7 features is not working on nodeJS `6.14.2` (this optimal version I guess)
